import nodemailer from 'nodemailer';

let transporter;

/**
 * Initializes (once) and returns a reusable transporter.
 */
function getTransporter() {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_EMAIL,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return transporter;
}

/**
 * Generic sendMail utility
 * @param {object} param0
 * @param {string|string[]} to
 * @param {string} subject
 * @param {string} html
 * @param {string} [text]
 */
export async function sendMail({ to, subject, html, text }) {
  try {
    const tx = getTransporter();
    await tx.sendMail({
      from: `"${process.env.APP_NAME || 'SOS System'}" <${process.env.SMTP_EMAIL}>`,
      to,
      subject,
      html,
      text,
    });
    return { success: true };
  } catch (error) {
    console.error('sendMail error:', error);
    return { success: false, error };
  }
}

/**
 * Helper to build a basic styled HTML wrapper
 */
export function wrapHtml(content) {
  return `
  <div style="font-family:Arial,sans-serif;line-height:1.5;color:#222;">
    ${content}
    <p style="margin-top:24px;font-size:12px;color:#666;">
      This message was generated by ${process.env.APP_NAME || 'SOS System'}.
    </p>
  </div>`;
}